Changed retain policy on base to unowned on dismissed event.
RxSwiftCommunity/RxFlow pull request #161
Opened 2020-10-14 19:42 UTC by BenMaer-Parkwood

Related to https://github.com/RxSwiftCommunity/RxFlow/issues/160

I changed the closure's retain policy on `base` to `unowned` so the `dismissed` event avoids retaining the base (UIViewController).

2020-10-18 21:16 UTC, twittemb requested changes

2020-10-18 21:16 UTC, twittemb commented on RxFlow/Extensions/Reactive+UIViewController.swift
> +            .filter { [unowned base] _ in base.isBeingDismissed }
I guess there is a very limited risk of crashing because of 'unowned' there, but perhaps using weak would be safer (considering that if base is nil, then it should have been dismissed). What do you think ?

`{ [weak base] _ in base?.isBeingDismissed ?? true }`

2020-10-19 17:04 UTC, BenMaer-Parkwood commented on RxFlow/Extensions/Reactive+UIViewController.swift
> +            .filter { [unowned base] _ in base.isBeingDismissed }
Okay, I agree. Although I believe that we wouldn't ever hit this closure without `base` being alive, I agree it's not worth risking in the case that I'm wrong.

I'll update my PR now.

2020-10-20 00:30 UTC, twittemb commented on RxFlow/Extensions/Reactive+UIViewController.swift
> +            .filter { [unowned base] _ in base.isBeingDismissed }
Looks good to me.
Thanks for you contribution.

2020-10-20 00:30 UTC, twittemb approved these changes

2020-10-20 00:30 UTC, merged